In [9]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [12]:
a = [1,2,2.5, "Hi"]
a

[1, 2, 2.5, 'Hi']

In [13]:
np.array(a)

array(['1', '2', '2.5', 'Hi'], dtype='<U32')

In [14]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [18]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [20]:
arr = np.ones((2,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr = np.linspace(1,5,100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [28]:
np.random.rand(10)

array([0.67293584, 0.70310805, 0.38335611, 0.36526935, 0.85840172,
       0.88117873, 0.99684008, 0.31184916, 0.57309034, 0.43251073])

In [29]:
np.random.randn(10)

array([-0.08487792, -0.3440295 , -0.22451125,  0.92993905, -0.09281014,
       -0.22527737,  0.08801424,  0.63869087, -0.71653829, -0.65914728])

In [33]:
np.random.randint(10,20,5)

array([16, 10, 13, 14, 16], dtype=int32)

**Array Attributes**

In [34]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.shape

(3, 3)

In [38]:
arr.size

10

In [39]:
arr.dtype

dtype('int64')

**Array Attributes**

In [48]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
arr.min()

np.int64(11)

In [50]:
arr.max()

np.int64(20)

In [51]:
arr.sum()

np.int64(155)

In [52]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.sum()

np.int64(45)

In [57]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [58]:
arr.mean()

np.float64(5.0)

In [59]:
arr.std()

np.float64(2.581988897471611)

In [60]:
arr.max()

np.int64(9)

In [61]:
arr.min()

np.int64(1)

In [62]:
arr.argmax()

np.int64(8)

In [64]:

arr.argmin()

np.int64(0)

**Reshaping And Resizing**

In [68]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [70]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

**Numpy Indexing And Slicing Of Vectors**

In [75]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
arr[6]

np.int64(17)

In [76]:
arr[1:4]

array([12, 13, 14])

In [78]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [79]:
arr[4]

np.int64(15)

**Numpy Indexing And Slicing Of Matrices**

In [81]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [95]:
row = arr[0]
row

array([1, 2, 3, 4, 5])

In [86]:
arr[0,0]

np.int64(1)

In [90]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [92]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [94]:
coloumn = arr[:,2]
coloumn

array([ 3,  8, 13, 18, 23, 28])

**Boolean Indexing**

In [97]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [102]:
bool_index = arr%2 == 0
bool_index 

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [103]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])