In [ ]:
import numpy an np

**Valid Sudoku**

In [4]:
s = np.array((
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],
    
    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
))

In [5]:
s.sum()

np.int64(405)

In [10]:
b = np.sum(s,axis = 1)
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [12]:
for i in b:
    if i != 45:
        print("Not Valid")
        break
else:
    print("Row is valid")

Row is valid


In [13]:
slice = s[0:3, 0:3]
slice

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [15]:
for i in range(0,9,3):
    for j in range (0,9,3): 
        n = s[i:i+3, j:j+3]
        print(n.sum())
        

45
45
45
45
45
45
45
45
45


**GENERAL QUESTIONS**

In [19]:
import numpy as np
#Columns : {Age, Math Marks, Science Marks}
data = np.array((
    [18,85,78],    #Student 1
    [19,92,88],    #Student 2
    [17,76,95],    #Student 3
    [18,65,70],    #Student 4
    [20,90,85]     #Student 5
))

In [21]:
#Get the shape of matrix.
data.shape

(5, 3)

In [23]:
#Find the Average Age of Students.
np.mean(data [:, 0])

np.float64(18.4)

In [25]:
#Extract math marks of All students.
data[:,1]

array([85, 92, 76, 65, 90])

In [27]:
#Find the Highet science MAx Marls. 
np.max(data[:,2])

np.int64(95)

In [32]:
#Get Details of the students who who scored more than 90 in maths. 
data[data[:,1]>90]

array([[19, 92, 88]])

In [36]:
#Incease maths Marks of of all students by 5.
math = data[:,1] + 5 
math

array([90, 97, 81, 70, 95])

In [42]:
#find  how many students are younger than 19. 
len(data[data[:,0]< 19])


3

In [45]:
#Calculate the Average Marks in each subject (Column wise mean). 
np.mean(data[:,1:], axis=0)

array([81.6, 83.2])

In [46]:
#Get data of Students who scored at least 80 in both subjects. 
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [60]:
#Replace All science marks < 75 with 0. 
data[:, 2][data[:, 2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])