**ARRAY OPERATINS**

*Arithmatic Operations*

In [1]:
import numpy as np

In [19]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
addition = a1 + a2
addition

array([ 7,  9, 11, 13, 15])

In [18]:
subtraction = a1 - a2
subtraction

array([-5, -5, -5, -5, -5])

In [22]:
multiplication = a1 * a2
multiplication

array([ 6, 14, 24, 36, 50])

In [23]:
division = a1 / a2
division

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [24]:
floorDivision = a1 // a2
floorDivision

array([0, 0, 0, 0, 0])

In [27]:
power = a1 ** a2
power

array([      1,     128,    6561,  262144, 9765625])

In [6]:
sum(a1+a2)

np.int64(55)

*Broadcasting*

In [29]:
l = [10,20,30,40]
arr = np.array(l)

In [30]:
arr + 10

array([20, 30, 40, 50])

In [32]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
arr2 = arr2+10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

*Deep And Shalow copy*

In [34]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
slice = a[:5]
slice 

array([1, 2, 3, 4, 5])

In [37]:
slice *10

array([10, 20, 30, 40, 50])

In [38]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
b = a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
b[0] = 100

In [42]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [48]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

no change 

In [45]:
b = a.copy()
b[0] = 50
b

array([50,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
a 

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

*Matric Opertion*

In [50]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [51]:
A

array([[1, 2],
       [3, 4]])

In [52]:
B

array([[5, 6],
       [7, 8]])

In [53]:
A + B

array([[ 6,  8],
       [10, 12]])

In [54]:
A - B

array([[-4, -4],
       [-4, -4]])

*Matrix Multiplication*

In [55]:
A @ B

array([[19, 22],
       [43, 50]])

In [58]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

*Transpose*

In [60]:
A.T

array([[1, 3],
       [2, 4]])

**Advance Array Multiplication**

*Stacking Array*

In [63]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [64]:
np.vstack((x , y))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
np.column_stack((x,y))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [70]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [73]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [74]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [76]:
a = np.vsplit(c,4)

In [77]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
